<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <name>JME OAuth2 Security Example</name>
    <description>Example OAuth2 clients and protected resources built with the jEAP security starter.</description>
    <modelVersion>4.0.0</modelVersion>
    <url>https://github.com/jme-admin-ch/jme-security-oauth2-example/tree/main</url>
    <scm>
        <url>https://github.com/jme-admin-ch/jme-security-oauth2-example.git</url>
        <connection>scm:git:git://github.com/jme-admin-ch/jme-security-oauth2-example.git</connection>
        <developerConnection>scm:git:ssh://github.com:jme-admin-ch/jme-security-oauth2-example.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <name>BIT</name>
            <email>jeap-community@bit.admin.ch</email>
            <organization>Federal Office of Information Technology, Systems and Telecommunication FOITT</organization>
            <organizationUrl>https://www.bit.admin.ch/</organizationUrl>
        </developer>
    </developers>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <parent>
        <groupId>ch.admin.bit.jeap</groupId>
        <artifactId>jeap-spring-boot-parent</artifactId>
        <version>38.0.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>ch.admin.bit.jeap</groupId>
    <artifactId>jme-security-oauth2-example</artifactId>
    <version>1.1.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <jeap-oauth-mock-server.version>8.0.1</jeap-oauth-mock-server.version>
        <jme-spring-boot-integration-test.version>5.8.0</jme-spring-boot-integration-test.version>
        <java.version>25</java.version>
        <maven.compiler.release>25</maven.compiler.release>
        <maven.javadoc.skip>true</maven.javadoc.skip>
    </properties>

    <modules>
        <module>jme-security-oauth2-auth-scs</module>
        <module>jme-security-oauth2-resource-service</module>
        <module>jme-security-oauth2-resource-authorities-service</module>
        <module>jme-security-oauth2-client-service</module>
        <module>jme-security-oauth2-client-authorities-service</module>
        <module>jme-security-oauth2-test</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>jme-security-oauth2-auth-scs</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>jme-security-oauth2-resource-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>jme-security-oauth2-resource-authorities-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>jme-security-oauth2-client-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>jme-security-oauth2-client-authorities-service</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Bundle-License>https://www.apache.org/licenses/LICENSE-2.0</Bundle-License>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.honton.chas</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-project-license</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/META-INF</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${maven.multiModuleProjectDirectory}</directory>
                                    <includes>
                                        <include>LICENSE</include>
                                    </includes>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>empty-javadoc-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <classifier>javadoc</classifier>
                            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                            <includes>
                                <include>META-INF/LICENSE</include>
                            </includes>
                            <forceCreation>true</forceCreation>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
